[package]
name = "trustfall-rustdoc-adapter"
version = "22.2.0"
edition = "2021"
authors = ["Predrag Gruevski <obi1kenobi82@gmail.com>"]
license = "Apache-2.0 OR MIT"
description = "Trustfall query adapter for rustdoc JSON data."
repository = "https://github.com/obi1kenobi/trustfall-rustdoc-adapter"
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trustfall_core = "0.0.7"
rustdoc-types = "0.18.0"

[dev-dependencies]
serde_json = "1.0.85"
serde = { version = "1.0.145", features = ["derive"] }
