# Pinning our toolchain ensures ./scripts/regenerate_test_rustdocs.sh always
# emits the desired format.

[toolchain]
# Pin to the latest nightly version that supports version 36.
channel = "nightly-2024-12-02"
