[package]
publish = false
name = "impl_for_ref"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dummy_ext = { path = "../dummy_ext" }
